booklibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import  settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("books.urls")),
    path('users/', include('users.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path
from . import views

app_name = "books"

urlpatterns = [
    path('', views.index, name="index" ),
    path('books/', views.books, name="book" ),
    path('book/<int:book_id>/', views.book, name="book_detail"),
    path('book/<slug:mode>/', views.filter_mode, name="filter_mode"),
    
]

users/urls.py
from os import name
from django.contrib.auth import urls
from . import views
from django.urls import path, include

app_name = "users"

urlpatterns = [

    path("", include(urls), name=urls),
    path("register/", views.register, name="register"),
    path("profile/<int:user_id>/", views.profile, name="profile"),

]

books/models.py
from django.db import models
from django.contrib.auth.models import User

TITLE_CHOICES = (
                ("scientific",'Scientific'),
                ('religious','Religious'),
                ('psychology',"Psychology"),
                ("roman","Roman") 
                    )

STATUS_CHOICES = (
                ("basy",'Basy'),
                ('free','Free'))

class Book(models.Model):
    name = models.CharField(max_length=50)
    author = models.CharField(max_length=20)
    price = models.PositiveSmallIntegerField()
    date_added = models.DateTimeField()
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="free")
    title = models.CharField(max_length=10, choices=TITLE_CHOICES, default="psychology")
    basy_user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    basy_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.name

class Comment(models.Model):
    body = models.CharField(max_length=200)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.body
    

    
class Image(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to=f'media/images/%Y/%m/%d/',blank=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)


    def __str__(self):
        return self.title

class RequestBook(models.Model):
    request_user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    requested_book = models.ForeignKey(Book, on_delete=models.CASCADE)
    text_to_admin = models.CharField(max_length=100, null=True)

    def __str__(self):
        return f'By : {self.request_user} for Book : {self.requested_book}'












        

users/models.py
from django.db import models

books/forms.py
from cProfile import label
from django import forms
from .models import Comment, RequestBook


class CommentForm(forms.ModelForm):
	""" creat topic for client """
	class Meta:
		""" auth elemans for form"""
		model = Comment
		fields = ['body']
		label = {'body': 'comment type : '}

class RequestForm(forms.ModelForm):
	""" creat topic for client """
	class Meta:
		""" auth elemans for form"""
		model = RequestBook
		fields = ['text_to_admin']
		label = {'text_to_admin': 'send request : '}		



		

books/views.py
from django.shortcuts import render, redirect
from .models import Book
from .forms import CommentForm, RequestForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

def index(request):
    return render(request, 'book/index.html')

@login_required
def books(request):
    book = Book.objects.order_by("-date_added")
    context = {"book":book}
    return render(request, 'book/books.html', context)

@login_required
def book(request,book_id):
    book = Book.objects.get(id=book_id)
    comments = book.comment_set.order_by("-date_added")[:10]
    img_obj = book.image_set.get()
    send = False

    if request.method != "POST":
        form = CommentForm()
        form2 = RequestForm()
    else:
        form = CommentForm(data=request.POST)
        form2 = RequestForm(data=request.POST)
        if form.is_valid():
            form2 = RequestForm()
            add_user = form.save(commit=False)
            add_user.author = request.user
            add_user.book = book
            add_user.save()
            return redirect("books:book_detail",book_id)
        elif form2.is_valid():
            form = CommentForm()
            send = True  
            add_user = form2.save(commit=False)
            add_user.request_user = request.user
            add_user.requested_book = book
            add_user.save()
            

    
    context = {"book":book,"comments":comments, "form":form,
    'img_obj':img_obj, "form2":form2,'send':send}
    return render(request, "book/book_detail.html", context)


@login_required
def filter_mode(request, mode):
    book = Book.objects.filter(title=mode).order_by('-date_added')
    context = {"book":book,"mode":mode}
    return render(request, 'book/books.html', context)

users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.models import User

def register(request):
    if request.method != "POST":   
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('books:index')
    context = {"form":form}
    return render(request, "registration/register.html", context)

def profile(request, user_id):
    user =   User.objects.get(id=user_id)
    books = user.book_set.all().order_by("-basy_date")

    context = {"user":user,"books":books}

    return render(request, "profile.html", context)

books/templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" >
    <title>Book Library</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 ">
        <a class="navbar-brand"  href="{% url 'books:index' %}">Library</a>
         <p>
            <button class="navbar-toggler btn btn-primary" type="button" data-toggle="collapse" data-target="#contentId" aria-expanded="false"
                    aria-controls="contentId" aria-label="toggler-navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </p>
        <div class="collapse navbar-collapse" id="contentId">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <div class="dropdown show">
                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Books
                        </a>
                      
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                          <a class="dropdown-item" href="{% url 'books:book' %}">All Books</a>
                          <a class="dropdown-item" href="{% url 'books:filter_mode' 'scientific' %}">Scientific</a>
                          <a class="dropdown-item" href="{% url 'books:filter_mode' 'religious' %}">Religious</a>
                          <a class="dropdown-item" href="{% url 'books:filter_mode' 'psychology' %}">Psychology</a>
                          <a class="dropdown-item" href="{% url 'books:filter_mode' 'roman' %}">Roman</a>
                        </div>
                      </div>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:profile' user.id %}">Hello , {{user.username}}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li> 
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">login</a> 
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a> 
                </li>
                {% endif %}
            </ul> 
        </div>
    </nav>
    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page-header %}
            
            {% endblock page-header %}
        </div>
        <div>
            {% block content %}
            
            {% endblock content %}
        </div>
    </main>
</body>
</html>

books/templates/book/book_detail.html
{% extends 'base.html' %}

{% block page-header %}


<h1>Details Book</h1>

<h2>book name : {{book}}</h2>

{% if img_obj %}
  
  <img src="{{ img_obj.image.url}}" alt="connect" style="max-height:200px">
{% endif %}

<ul>
    <li>
        <p>
            Author : {{book.author}}
        </p>
    </li>
    <li>
        <p>
            Status : {{book.status}}
        </p>
    </li>
    <li>
        <p>
            Price : {{book.price}}
        </p>
    </li>
    <li>
        <p>
           Title : {{book.title}} 
        </p>
    </li>

</ul>

{% if send %}
    <h6>your request sended for admin!</h6>
{% else %}
<h6>send your for give this book</h6>
<form action="{% url 'books:book_detail' book.id %}" method="post">
    {{form2.as_p}}
    {% csrf_token %}
    <button name="submit">send request</button>
</form>
{% endif %}

{% endblock page-header %}


{% block content %}



<h3>comments:</h3>

<ul>
    {% for comment in comments %}
    <li>
        <h5>commented by : {{comment.author}}</h5>
        
            <p>comment : {{comment}}</p>
            <p>at : {{ comment.date_added|date:'M d, Y H:i' }}</p>
        
    </li>
    {%empty%}
        <li>
            creat first comment .
        </li>
    {% endfor %}

    


</ul>

<form action="{% url 'books:book_detail' book.id %}" method="post">

    {{form.as_p}}
    {% csrf_token %}
    <button name="submit">add comment</button>
</form>

<ol>
{% for p in person %}
    <li>
    <h6>give this book by : {{p}}</h6>
    </li>
{% endfor %}
</ol>


{% endblock content %}

books/templates/book/books.html
{% extends 'base.html' %}


{% block page-header %}



<p class="lead">
  <a class="btn btn-primary btn-lg" href="{% url 'books:book' %}" role="button">Books</a>
</p>

{% if mode %}
    <h6>mode : {{mode}}</h6>

{% else %}

<h6>mode : All Books</h6>

{% endif %}


{% endblock page-header %}




{% block content %}




    
<div class="row">
  



    {% for b in book %}
    <div class="col-sm-6">
    <div class="card" style="max-width:350px">
      <img class="card-img-top" src="{{ b.image_set.get.image.url}}" alt="{{b.name}}">
      <div class="card-body">
        <h4 class="card-title">{{b.name}}</h4>
        <p class="card-text">Some example text.</p>
        <a href="{% url 'books:book_detail' b.id %}">See Book</a>
      </div>
    </div>
  </div>


    {% empty %}

    
     <h3>   creat new book </h3>
    

    {% endfor %}

</div>
    {% endblock content %}

books/templates/book/index.html
{% extends 'base.html' %}

{% block page-header %}
<div class="jumbotron">
    <h1 class="display-3">Start your reading
    </h1>
    <p class="lead">creat your account to see books</p>
    <hr class="my-2">
    <p>More info</p>
    <p class="lead">
        <a class="btn btn-primary btn-lg" href="{% url 'users:register' %}" role="button">Register</a>
    </p>
</div>


{% endblock page-header %}

{% block content %}

<p class="lead">
    <a class="btn btn-primary btn-lg" href="{% url 'books:book' %}" role="button">Books</a>
</p>

{% endblock content %} 

users/templates/profile.html
{% extends 'base.html' %}


{% block page-header %}

<h2>Profile : {{user.username}}</h2>

{% endblock page-header %}

{% block content %}
<h4>basy books for this user : </h4>
<ol>
{% for b in books %}
    <li>
       <p><a href="{% url 'books:book_detail' b.id %}">{{b.name}}</a></p>
       <p>at : {{ b.basy_date|date:'M d, Y H:i' }}</p>
    </li>
{% endfor %}
</ol>

{% endblock content %}